### ISSUE TITLE
/etc/storage/v2ray/sh-whitelist.sh 中对 /media/AiDisk_a1 的文件夹书写错误，以及一些建议。

### ISSUE THREAD

**Issue by zhukai1998** [ntgeralt/v2ray-for-padavan#1]
首先非常感谢前辈的分享。
  如题，我在使用过程中遇到一些问题，现已解决。
  _1、/etc/storage/v2ray/**sh-whitelist.sh**_ 中对 /media/**AiDisk_a1** 的文件夹书写错误，如下图。
  ![1](https://user-images.githubusercontent.com/43125027/72263456-dc093d80-3653-11ea-9d6f-432b26378904.png)
  ![2](https://user-images.githubusercontent.com/43125027/72263483-e9262c80-3653-11ea-9a9c-bb07a652342a.jpg)
  2、若是使用者的路由器没有 USB 接口的话，每次路由器重启 /media 下的文件都会被擦除，若是可以的话，也可以把所有的文件都放到 /etc/storage/v2ray/ 下，然后更改一些配置文件就可以。我采用的文件列表如下图。
  ![3](https://user-images.githubusercontent.com/43125027/72263700-59cd4900-3654-11ea-9c3e-bdcdbefe367b.jpg)
  修改的代码我就不班门弄斧了。
  这是个人的一些拙见，若有不当之处，还望前辈见谅。

**Comment by ntgeralt** [comment]
是有一些坑，如TF卡路径也会不同，我看这里比较冷清没处理。想着你们会玩的应该会自行处理 ；

你算是第一位反映，有空我再好好完善下  ：）

**Comment by binbin6106** [comment]
做个软链接不可以吗
