### ISSUE TITLE
TMP的GFWLIST模式发现无法使用youtube的app与google.com

### ISSUE THREAD

**Issue by ztj7728** [ntgeralt/v2ray-for-padavan#2]
TMP的GFWLIST该模式下，可以访问youtube.com，与google.co.jp。
但是无法使用youtube的app，无法访问google.com，
试过google.com/ncr（no country redirect），也是不行。

我通过抓包，发现访问google.com和youtube app的时候有UDP请求，而且失败了，怀疑是否是不转发UDP导致的？ 或者是与dns有关？
不知道如何解决？ 想请大佬看下，谢谢。

**Comment by ntgeralt** [comment]
https://github.com/ntgeralt/v2ray-for-padavan/tree/master/FOR-USB-or-TF/FOR-USB-or-TF/media/AiDisk_a1/v2ray/example-config

有些例程你参考下。

我测试了ws tls模式，ios YouTube APP正常。google.com也正常访问，至于不正常有可能之前DNS污染，开关飞行模式或重启解决。

V2Ray json有sniffing嗅探域名，所以我没弄DNS那块
