### ISSUE TITLE
抱歉，小白提问，config.json如何调整才好？

### ISSUE THREAD

**Issue by lifewinnerP11** [ntgeralt/v2ray-for-padavan#3]
自己的config.json 有没有模板制作呀
导出了电脑端v2rayng的json
照猫画虎做出来的文件，不好使

**Comment by ntgeralt** [comment]
https://github.com/ntgeralt/v2ray-for-padavan/tree/master/FOR-USB-or-TF/FOR-USB-or-TF/media/AiDisk_a1/v2ray/example-config

有些例程你参考下。用Notepad++ 一行行改，换成你梯子的话，大概三四行。
